# Generated by Django 2.2.16 on 2023-06-13 07:59

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rentals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(default=datetime.datetime(2023, 6, 13, 7, 59, 27, 285984, tzinfo=utc), verbose_name='Время аренды')),
                ('return_date', models.DateTimeField(default=datetime.datetime(2023, 6, 27, 7, 59, 27, 286002, tzinfo=utc), verbose_name='Дата возврата')),
                ('books', models.ManyToManyField(to='book.Book', verbose_name='Аренда книг')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book', to=settings.AUTH_USER_MODEL, verbose_name='Читатель')),
            ],
        ),
    ]
