# Generated by Django 3.2.19 on 2023-06-13 10:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0003_auto_20230613_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentals',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 13, 10, 38, 52, 287762, tzinfo=utc), verbose_name='Время аренды'),
        ),
        migrations.AlterField(
            model_name='rentals',
            name='return_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 27, 10, 38, 52, 287778, tzinfo=utc), verbose_name='Дата возврата'),
        ),
    ]
