# Generated by Django 3.2.19 on 2023-06-13 16:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0008_auto_20230613_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentals',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 13, 16, 0, 17, 576225, tzinfo=utc), verbose_name='Время аренды'),
        ),
        migrations.AlterField(
            model_name='rentals',
            name='return_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 27, 16, 0, 17, 576242, tzinfo=utc), verbose_name='Дата возврата'),
        ),
    ]
