# Generated by Django 3.2.19 on 2023-06-14 10:55

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20230613_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularityBook',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('views', models.IntegerField(default=0, verbose_name='Популярность')),
                ('date_create', models.DateField(default=datetime.datetime(2023, 6, 14, 10, 55, 22, 451987, tzinfo=utc))),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.book', verbose_name='Книга')),
            ],
        ),
    ]
