# Generated by Django 3.2.19 on 2023-06-14 12:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_popularitybook'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='popularitybook',
            options={'verbose_name': 'Статистика', 'verbose_name_plural': 'Статистика'},
        ),
        migrations.AlterField(
            model_name='popularitybook',
            name='date_create',
            field=models.DateField(default=datetime.datetime(2023, 6, 14, 12, 23, 43, 311556, tzinfo=utc), verbose_name='Дата первой аренды'),
        ),
    ]
