# Generated by Django 3.2.19 on 2023-06-14 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_auto_20230614_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='views',
            field=models.IntegerField(default=0, verbose_name='Популярность'),
        ),
        migrations.DeleteModel(
            name='PopularityBook',
        ),
    ]
