# Generated by Django 3.2.19 on 2023-06-14 12:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_auto_20230614_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='date_create',
            field=models.DateField(default=datetime.datetime(2023, 6, 14, 12, 47, 6, 920355, tzinfo=utc)),
        ),
    ]
